# change the followings to match your Github username and repo name
baseurl: "/dumpsterdive" # the name of your github repo
url: "https://www.dumpsterdivedata.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Dumpster Diving For Data"
description: Adventures in a World of Dirty Data

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Brick
author-bio: false  # change to false to hide
author-image: logo_transparent.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: Adventures
  permalink: Adventures
- text: Shirts
  permalink: Shirts
- text: Contact
  permalink: Contact

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: mailto:brick@dumpsterdivedata.com

# footer information
footer-msg: "Powered by Your Trash"
footer-msg-link: https://dumpsterdivedata.com

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
