# change the followings to match your Github username and repo name
baseurl: "/dumpsterdive" # the name of your github repo
url: "https://usernameJones.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Dumpster Diving For Data"
description: Adventures in a World of Dirty Data

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Brick
author-bio: false  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: brick@dumpsterdivedata.com

# footer information
footer-msg: "Powered by your trash"
footer-msg-link: https:/dumpsterdivedata.com

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
